// <auto-generated />
using Ledinpro.Data;
using Ledinpro.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Ledinpro.Migrations
{
    [DbContext(typeof(LedinproContext))]
    [Migration("20180528031225_AddMenuContext")]
    partial class AddMenuContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Ledinpro.Models.Carousel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<string>("Description");

                    b.Property<DateTime?>("LastEditDateTime");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(255);

                    b.Property<string>("MobilePicturePath");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("PicturePath")
                        .IsRequired();

                    b.Property<Guid>("RelativeProductId");

                    b.Property<string>("SortNumber");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Carousel");
                });

            modelBuilder.Entity("Ledinpro.Models.CompanyInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("BackgroundImage");

                    b.Property<DateTime?>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<DateTime?>("LastEditDateTime");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("CompanyInfo");
                });

            modelBuilder.Entity("Ledinpro.Models.Logo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime?>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("LastEditDateTime");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(255);

                    b.Property<string>("LogoPath");

                    b.Property<string>("LogoType");

                    b.HasKey("Id");

                    b.ToTable("Logo");
                });

            modelBuilder.Entity("Ledinpro.Models.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("LastEditDateTime");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(255);

                    b.Property<string>("Link")
                        .IsRequired();

                    b.Property<int>("Sortnumber");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Ledinpro.Models.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime?>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("LastEditDateTime");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(255);

                    b.Property<bool>("PublishOrNot");

                    b.Property<DateTime?>("PublishTime");

                    b.Property<string>("SubTitle")
                        .HasMaxLength(255);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Ledinpro.Models.PreviewProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("LastEditDateTime");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(255);

                    b.Property<string>("MobilePicturePath");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("PicturePath");

                    b.Property<Guid>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PreviewProduct");
                });

            modelBuilder.Entity("Ledinpro.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<DateTime?>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<string>("Description");

                    b.Property<string>("Dimming");

                    b.Property<string>("Efficient");

                    b.Property<string>("Heat")
                        .HasMaxLength(64);

                    b.Property<string>("InputPower")
                        .HasMaxLength(64);

                    b.Property<string>("InputVoltage")
                        .HasMaxLength(64);

                    b.Property<DateTime?>("LastEditDateTime");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(255);

                    b.Property<string>("LightingAngle");

                    b.Property<string>("Lumen");

                    b.Property<string>("MobilePicturePath");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("OutputPower")
                        .HasMaxLength(64);

                    b.Property<string>("OutputVoltage")
                        .HasMaxLength(64);

                    b.Property<string>("PicturePath");

                    b.Property<string>("Power");

                    b.Property<string>("Ppf")
                        .HasMaxLength(255);

                    b.Property<string>("Specification");

                    b.Property<string>("Spectrum");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<string>("Weight")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Ledinpro.Models.ProductComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment")
                        .IsRequired();

                    b.Property<DateTime?>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("LastEditDateTime");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(255);

                    b.Property<Guid>("ProductId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductComment");
                });

            modelBuilder.Entity("Ledinpro.Models.ProductFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("LastEditDateTime");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("PicturePath");

                    b.Property<Guid>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFeature");
                });

            modelBuilder.Entity("Ledinpro.Models.ProductFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<string>("FilePath");

                    b.Property<int>("FileTpye");

                    b.Property<DateTime?>("LastEditDateTime");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(255);

                    b.Property<Guid>("ProductId");

                    b.Property<string>("Version")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFile");
                });

            modelBuilder.Entity("Ledinpro.Models.ProductScene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime?>("LastEditDateTime");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(255);

                    b.Property<string>("MobilePicturePath");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("PicturePath");

                    b.Property<string>("SceneType");

                    b.HasKey("Id");

                    b.ToTable("ProductScene");
                });

            modelBuilder.Entity("Ledinpro.Models.ProductSceneProduct", b =>
                {
                    b.Property<Guid>("ProductSceneId");

                    b.Property<Guid>("ProductId");

                    b.HasKey("ProductSceneId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSceneProduct");
                });

            modelBuilder.Entity("Ledinpro.Models.SaleContactInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<bool>("IsShow");

                    b.Property<DateTime?>("LastEditDateTime");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("NickName")
                        .HasMaxLength(64);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("PicturePath");

                    b.Property<string>("Skype")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("SaleContactInfo");
                });

            modelBuilder.Entity("Ledinpro.Models.SubProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("ColorAngle")
                        .HasMaxLength(64);

                    b.Property<DateTime?>("CreateDateTime");

                    b.Property<string>("CreateUserName")
                        .HasMaxLength(255);

                    b.Property<string>("Dimming")
                        .HasMaxLength(64);

                    b.Property<string>("Efficient")
                        .HasMaxLength(64);

                    b.Property<string>("InputPower")
                        .HasMaxLength(64);

                    b.Property<DateTime?>("LastEditDateTime");

                    b.Property<string>("LastEditUserName")
                        .HasMaxLength(255);

                    b.Property<string>("Lumen")
                        .HasMaxLength(64);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("OutputPower")
                        .HasMaxLength(64);

                    b.Property<string>("PicturePath");

                    b.Property<Guid>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("SubProduct");
                });

            modelBuilder.Entity("Ledinpro.Models.PreviewProduct", b =>
                {
                    b.HasOne("Ledinpro.Models.Product", "Product")
                        .WithMany("PreviewProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ledinpro.Models.ProductComment", b =>
                {
                    b.HasOne("Ledinpro.Models.Product")
                        .WithMany("ProductComments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ledinpro.Models.ProductFeature", b =>
                {
                    b.HasOne("Ledinpro.Models.Product", "Product")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ledinpro.Models.ProductFile", b =>
                {
                    b.HasOne("Ledinpro.Models.Product", "Product")
                        .WithMany("ProductFiles")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ledinpro.Models.ProductSceneProduct", b =>
                {
                    b.HasOne("Ledinpro.Models.Product", "Product")
                        .WithMany("ProductSceneProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ledinpro.Models.ProductScene", "ProductScene")
                        .WithMany("ProductSceneProducts")
                        .HasForeignKey("ProductSceneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ledinpro.Models.SubProduct", b =>
                {
                    b.HasOne("Ledinpro.Models.Product", "Product")
                        .WithMany("SubProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
